hydra:
  hydra_logging:
    disable_existing_loggers: false
  run:
    dir: .

hardware:
  nb_cpu: 4
  nb_gpu: 1

dataset:
  dataset: ubs8k
  num_classes: 10

model:
  model: wideresnet28_2

train_param:
  supervised_ratio: 0.1
  batch_size: 64
  nb_epoch: 200
  learning_rate: 0.001
  seed: 1234
  resume: false

  # These two parameters bellow are used for UrbanSound8k and ESC cross validation
  train_folds: [1,2,3,4,5,6,7,8,9]
  val_folds: [10]

# Mean teacher parameters
mt:
  alpha: 0.999
  warmup_length: 50
  lambda_ccost_max: 1
  use_softmax: true
  ccost_method: mse

# MixUp parameters
mixup:
  use: false
  alpha: 1.0
  max: true
  label: true

path:
  dataset_root: ../../datasets
  checkpoint_root: ../../model_save
  tensorboard_root: ../../tensorboard
  checkpoint_path: ${path.checkpoint_root}/${dataset.dataset}/mean-teacher
  tensorboard_path: ${path.tensorboard_root}/${dataset.dataset}/mean-teacher
